# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Piggy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Piggy

  target 'PiggyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PiggyUITests' do
    # Pods for testing
  end

end
