# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'Piggy' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Piggy

pod 'Appirater'

# Firebase
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Storage'

# Google Sign In
pod 'GoogleSignIn'

# MaterialDesign
pod 'MaterialComponents/TextControls+FilledTextAreas'
pod 'MaterialComponents/TextControls+FilledTextFields'
pod 'MaterialComponents/TextControls+OutlinedTextAreas'
pod 'MaterialComponents/TextControls+OutlinedTextFields'


  target 'PiggyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PiggyUITests' do
    # Pods for testing
  end

end
